# Generated by Django 5.0 on 2025-06-10 13:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX')], max_length=4)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('extracted_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_results', to='detector.document')),
            ],
        ),
    ]
